# Chapter 2 Assignment #

## by Jess Kuhn ##

In [6]:
import pandas as pd

In [8]:
RR = pd.read_csv('ramen-ratings.csv')
RR.head()

,Brand,Variety,Style,Country,Stars
0,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75
1,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1.00
2,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25
3,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75
4,Ching's Secret,Singapore Curry,Pack,India,3.75

In [10]:
RR.tail()

,Brand,Variety,Style,Country,Stars
2572,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.5
2573,Wai Wai,Oriental Style Instant Noodles,Pack,Thailand,1.0
2574,Wai Wai,Tom Yum Shrimp,Pack,Thailand,2.0
2575,Wai Wai,Tom Yum Chili Flavor,Pack,Thailand,2.0
2576,Westbrae,Miso Ramen,Pack,USA,0.5

In [16]:
RR.Stars.describe()

count    2577.000000
mean        3.654676
std         1.015331
min         0.000000
25%         3.250000
50%         3.750000
75%         4.250000
max         5.000000
Name: Stars, dtype: float64

In [12]:
RR.nunique()

Brand       355
Variety    2410
Style         7
Country      38
Stars        42
dtype: int64

In [14]:
RR.loc[RR.Country == 'Vietnam']

,Brand,Variety,Style,Country,Stars
18,Binh Tay,Mi Hai Cua,Pack,Vietnam,4.00
52,Uni-President,Mushroom Flavor,Pack,Vietnam,0.00
143,Mum Ngon,Lau Tom Chua Cay,Pack,Vietnam,3.50
224,Vifon,Viet Cuisine Bun Rieu Cua Sour Crab Soup Insta...,Bowl,Vietnam,5.00
365,Acecook,Oh! Ricey Pork Flavour,Pack,Vietnam,4.00
...,...,...,...,...,...
2486,Binh Tay,Mi Chay Mushroom,Pack,Vietnam,2.75
2535,Ve Wong,Kung-Fu Chicken Flavor,Pack,Vietnam,2.75
2570,Ve Wong,Mushroom Pork,Pack,Vietnam,1.00
2571,Vifon,Nam Vang,Pack,Vietnam,2.50
2572,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.50

In [16]:
RR.loc[:, ['Brand', 'Style']]

               Brand Style
0          New Touch   Cup
1           Just Way  Pack
2             Nissin   Cup
3            Wei Lih  Pack
4     Ching's Secret  Pack
...              ...   ...
2572           Vifon  Bowl
2573         Wai Wai  Pack
2574         Wai Wai  Pack
2575         Wai Wai  Pack
2576        Westbrae  Pack

[2577 rows x 2 columns]

In [18]:
RR.Country

0          Japan
1         Taiwan
2            USA
3         Taiwan
4          India
          ...
2572     Vietnam
2573    Thailand
2574    Thailand
2575    Thailand
2576         USA
Name: Country, Length: 2577, dtype: object

In [34]:
RR.sort_values('Stars', descending=True)

TypeError: DataFrame.sort_values() got an unexpected keyword argument 'descending'

In [22]:
RR.Country.replace({'USA' : 'United States'}, inplace = True)

In [24]:
RR.to_csv('Edited-Ramen-Ratings.csv', index = False)

In [26]:
NRR = pd.read_csv('Edited-Ramen-Ratings.csv')

In [28]:
NRR.head()

,Brand,Variety,Style,Country,Stars
0,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75
1,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1.00
2,Nissin,Cup Noodles Chicken Vegetable,Cup,United States,2.25
3,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75
4,Ching's Secret,Singapore Curry,Pack,India,3.75

In [30]:
NRR.Country.nunique()

37

In [32]:
NRR.groupby('Country').mean('Stars').sort_values('Stars', ascending = False).head(3)

             Stars
Country
Brazil    4.350000
Sarawak   4.333333
Cambodia  4.200000

In [34]:
NRR.groupby('Country').mean('Stars').sort_values('Stars', ascending = True).head(3)

                Stars
Country
Nigeria      1.500000
Canada       2.243902
Netherlands  2.483333

In [36]:
%%time
NRR.groupby('Country').mean('Stars').sort_values('Stars', ascending = True).head(3)

CPU times: total: 0 ns
Wall time: 4 ms

                Stars
Country
Nigeria      1.500000
Canada       2.243902
Netherlands  2.483333